#!/command/with-contenv sh
# WORKER SERVICE
# Runs the Sidekiq background processor

cd /rails

# We wait for the web server or DB to be potentially ready (optional but safer)
sleep 2

# Execute the sidekiq worker
# Sidekiq handles transaction processing and syncs
exec bundle exec sidekiq
